"""Exploratory analysis for sentiment and trader-performance relationships."""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

os.environ.setdefault("LOKY_MAX_CPU_COUNT", "1")

from scipy import stats
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler


LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class AnalysisResults:
    """Named analysis tables generated by the EDA pipeline."""

    distribution_summary: pd.DataFrame
    correlation_matrix: pd.DataFrame
    sentiment_profitability: pd.DataFrame
    leverage_by_sentiment: pd.DataFrame
    symbol_performance: pd.DataFrame


@dataclass(frozen=True)
class AdvancedAnalyticsResults:
    """Advanced trader analytics and statistical test outputs."""

    trader_clusters: pd.DataFrame
    top_traders: pd.DataFrame
    worst_traders: pd.DataFrame
    statistical_tests: pd.DataFrame
    sentiment_comparisons: pd.DataFrame


def _profit_factor(closed_pnl: pd.Series) -> float:
    """Calculate gross profit divided by absolute gross loss."""
    gross_profit = closed_pnl[closed_pnl > 0].sum()
    gross_loss = closed_pnl[closed_pnl < 0].sum()
    if gross_loss < 0:
        return float(gross_profit / abs(gross_loss))
    if gross_profit > 0:
        return float("inf")
    return 0.0


def _win_rate(closed_pnl: pd.Series) -> float:
    """Calculate the share of profitable trades."""
    if closed_pnl.empty:
        return np.nan
    return float((closed_pnl > 0).mean())


def summarize_distributions(
    trade_sentiment: pd.DataFrame,
    daily_sentiment: pd.DataFrame,
    trader_metrics: pd.DataFrame,
) -> pd.DataFrame:
    """Create distribution summaries for key numeric metrics."""
    sources = {
        "trade": trade_sentiment,
        "daily": daily_sentiment,
        "trader": trader_metrics,
    }
    rows: list[dict[str, float | str]] = []

    for source_name, dataframe in sources.items():
        numeric_columns = dataframe.select_dtypes(include=[np.number]).columns
        for column in numeric_columns:
            series = dataframe[column].replace([np.inf, -np.inf], np.nan).dropna()
            if series.empty:
                continue
            description = series.describe(percentiles=[0.25, 0.5, 0.75])
            rows.append(
                {
                    "source": source_name,
                    "metric": column,
                    "count": float(description["count"]),
                    "mean": float(description["mean"]),
                    "std": float(description.get("std", np.nan)),
                    "min": float(description["min"]),
                    "p25": float(description["25%"]),
                    "median": float(description["50%"]),
                    "p75": float(description["75%"]),
                    "max": float(description["max"]),
                }
            )

    return pd.DataFrame(rows)


def compute_correlations(daily_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Compute Pearson correlations for daily numeric metrics."""
    numeric = daily_sentiment.select_dtypes(include=[np.number]).replace(
        [np.inf, -np.inf],
        np.nan,
    )
    numeric = numeric.dropna(axis=1, how="all")
    if numeric.shape[1] < 2:
        return pd.DataFrame()
    return numeric.corr(method="pearson")


def analyze_profitability_by_sentiment(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Compare trade profitability across sentiment classifications."""
    required_columns = {"classification", "closed_pnl"}
    missing_columns = sorted(required_columns - set(trade_sentiment.columns))
    if missing_columns:
        raise ValueError(f"Trade-sentiment data is missing columns: {missing_columns}")

    data = trade_sentiment.copy()
    data["classification"] = data["classification"].fillna("Unknown")
    grouped = data.groupby(["classification", "sentiment_score"], dropna=False)
    summary = grouped.agg(
        trades=("closed_pnl", "size"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        median_pnl=("closed_pnl", "median"),
        win_rate=("closed_pnl", _win_rate),
        pnl_volatility=("closed_pnl", lambda values: float(values.std(ddof=0))),
        avg_leverage=("leverage", "mean"),
        avg_size=("size", "mean"),
    ).reset_index()
    profit_factor = grouped["closed_pnl"].apply(_profit_factor).reset_index()
    profit_factor = profit_factor.rename(columns={"closed_pnl": "profit_factor"})
    summary = summary.merge(
        profit_factor,
        on=["classification", "sentiment_score"],
        how="left",
    )
    return summary.sort_values("sentiment_score", na_position="last").reset_index(drop=True)


def analyze_leverage_behavior(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Summarize leverage usage and outcomes by sentiment and leverage bucket."""
    required_columns = {"classification", "leverage_bucket", "closed_pnl"}
    missing_columns = sorted(required_columns - set(trade_sentiment.columns))
    if missing_columns:
        raise ValueError(f"Trade-sentiment data is missing columns: {missing_columns}")

    data = trade_sentiment.copy()
    data["classification"] = data["classification"].fillna("Unknown")
    data["leverage_bucket"] = data["leverage_bucket"].fillna("unknown")

    summary = data.groupby(
        ["classification", "sentiment_score", "leverage_bucket"],
        dropna=False,
    ).agg(
        trades=("closed_pnl", "size"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        win_rate=("closed_pnl", _win_rate),
        avg_leverage=("leverage", "mean"),
    ).reset_index()
    return summary.sort_values(
        ["sentiment_score", "leverage_bucket"],
        na_position="last",
    ).reset_index(drop=True)


def analyze_symbol_performance(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Rank symbols by profitability and trading behavior."""
    required_columns = {"symbol", "account", "closed_pnl"}
    missing_columns = sorted(required_columns - set(trade_sentiment.columns))
    if missing_columns:
        raise ValueError(f"Trade-sentiment data is missing columns: {missing_columns}")

    summary = trade_sentiment.groupby("symbol", dropna=False).agg(
        trades=("closed_pnl", "size"),
        active_traders=("account", "nunique"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        median_pnl=("closed_pnl", "median"),
        win_rate=("closed_pnl", _win_rate),
        avg_leverage=("leverage", "mean"),
        avg_size=("size", "mean"),
    ).reset_index()
    return summary.sort_values("total_pnl", ascending=False).reset_index(drop=True)


def run_exploratory_analysis(
    trade_sentiment: pd.DataFrame,
    daily_sentiment: pd.DataFrame,
    trader_metrics: pd.DataFrame,
) -> AnalysisResults:
    """Run the complete exploratory analysis suite."""
    results = AnalysisResults(
        distribution_summary=summarize_distributions(
            trade_sentiment,
            daily_sentiment,
            trader_metrics,
        ),
        correlation_matrix=compute_correlations(daily_sentiment),
        sentiment_profitability=analyze_profitability_by_sentiment(trade_sentiment),
        leverage_by_sentiment=analyze_leverage_behavior(trade_sentiment),
        symbol_performance=analyze_symbol_performance(trade_sentiment),
    )
    LOGGER.info("Generated exploratory analysis tables")
    return results


def save_analysis_tables(results: AnalysisResults, output_dir: Path) -> None:
    """Persist EDA tables as CSV files for review and reporting."""
    output_dir.mkdir(parents=True, exist_ok=True)
    for table_name, dataframe in results.__dict__.items():
        dataframe.to_csv(output_dir / f"{table_name}.csv", index=True)


def cluster_traders(trader_metrics: pd.DataFrame, n_clusters: int = 4) -> pd.DataFrame:
    """Cluster traders by performance and behavior metrics."""
    if trader_metrics.empty:
        return trader_metrics.copy()

    numeric_columns = [
        "total_trades",
        "win_rate",
        "avg_pnl",
        "total_pnl",
        "avg_leverage",
        "buy_sell_ratio",
        "avg_size",
        "pnl_volatility",
        "profit_factor",
    ]
    available_columns = [column for column in numeric_columns if column in trader_metrics.columns]
    clustered = trader_metrics.copy()
    if not available_columns or len(clustered) < 2:
        clustered["cluster"] = 0
        return clustered

    features = clustered[available_columns].replace([np.inf, -np.inf], np.nan)
    features = features.apply(lambda column: column.fillna(column.median()), axis=0)
    features = features.fillna(0.0)

    cluster_count = min(n_clusters, len(clustered))
    scaled_features = StandardScaler().fit_transform(features)
    model = KMeans(n_clusters=cluster_count, random_state=42, n_init=10)
    clustered["cluster"] = model.fit_predict(scaled_features)
    return clustered.sort_values(["cluster", "total_pnl"], ascending=[True, False])


def rank_traders(
    trader_metrics: pd.DataFrame,
    ranking_column: str = "total_pnl",
    top_n: int = 10,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return top and worst traders by the requested ranking column."""
    if trader_metrics.empty or ranking_column not in trader_metrics.columns:
        return pd.DataFrame(), pd.DataFrame()

    ranked = trader_metrics.sort_values(ranking_column, ascending=False)
    top_traders = ranked.head(top_n).reset_index(drop=True)
    worst_traders = ranked.tail(top_n).sort_values(ranking_column).reset_index(drop=True)
    return top_traders, worst_traders


def run_statistical_tests(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Run statistical tests comparing trader outcomes across sentiment regimes."""
    if trade_sentiment.empty:
        return pd.DataFrame()

    rows: list[dict[str, float | str]] = []
    data = trade_sentiment.copy()
    data["classification"] = data["classification"].fillna("Unknown")

    pnl_groups = [
        group["closed_pnl"].dropna()
        for _, group in data.groupby("classification")
        if len(group["closed_pnl"].dropna()) >= 2
    ]
    if len(pnl_groups) >= 2:
        statistic, p_value = stats.kruskal(*pnl_groups)
        rows.append(
            {
                "test": "Kruskal-Wallis PnL by sentiment",
                "statistic": float(statistic),
                "p_value": float(p_value),
                "interpretation": "PnL distributions differ by sentiment"
                if p_value < 0.05
                else "No significant PnL distribution difference detected",
            }
        )

    leverage_groups = [
        group["leverage"].dropna()
        for _, group in data.groupby("classification")
        if "leverage" in group and len(group["leverage"].dropna()) >= 2
    ]
    if len(leverage_groups) >= 2:
        statistic, p_value = stats.kruskal(*leverage_groups)
        rows.append(
            {
                "test": "Kruskal-Wallis leverage by sentiment",
                "statistic": float(statistic),
                "p_value": float(p_value),
                "interpretation": "Leverage usage differs by sentiment"
                if p_value < 0.05
                else "No significant leverage difference detected",
            }
        )

    if {"sentiment_score", "closed_pnl"}.issubset(data.columns):
        paired = data[["sentiment_score", "closed_pnl"]].dropna()
        if len(paired) >= 3:
            statistic, p_value = stats.spearmanr(
                paired["sentiment_score"],
                paired["closed_pnl"],
            )
            rows.append(
                {
                    "test": "Spearman sentiment score vs PnL",
                    "statistic": float(statistic),
                    "p_value": float(p_value),
                    "interpretation": "Sentiment score is associated with PnL"
                    if p_value < 0.05
                    else "No significant sentiment-PnL association detected",
                }
            )

    if {"sentiment_score", "leverage"}.issubset(data.columns):
        paired = data[["sentiment_score", "leverage"]].dropna()
        if len(paired) >= 3:
            statistic, p_value = stats.spearmanr(
                paired["sentiment_score"],
                paired["leverage"],
            )
            rows.append(
                {
                    "test": "Spearman sentiment score vs leverage",
                    "statistic": float(statistic),
                    "p_value": float(p_value),
                    "interpretation": "Sentiment score is associated with leverage"
                    if p_value < 0.05
                    else "No significant sentiment-leverage association detected",
                }
            )

    return pd.DataFrame(rows)


def compare_sentiment_groups(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Create side-by-side sentiment comparisons for performance and behavior."""
    if trade_sentiment.empty:
        return pd.DataFrame()

    data = trade_sentiment.copy()
    data["classification"] = data["classification"].fillna("Unknown")
    summary = data.groupby(["classification", "sentiment_score"], dropna=False).agg(
        trades=("closed_pnl", "size"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        win_rate=("closed_pnl", _win_rate),
        avg_leverage=("leverage", "mean"),
        buy_share=("trade_direction", lambda values: float((values == "buy").mean())),
        avg_size=("size", "mean"),
    ).reset_index()

    neutral_avg = summary.loc[
        summary["classification"] == "Neutral",
        "avg_pnl",
    ]
    baseline = float(neutral_avg.iloc[0]) if not neutral_avg.empty else float(summary["avg_pnl"].mean())
    summary["avg_pnl_vs_neutral"] = summary["avg_pnl"] - baseline
    return summary.sort_values("sentiment_score", na_position="last").reset_index(drop=True)


def run_advanced_analytics(
    trade_sentiment: pd.DataFrame,
    trader_metrics: pd.DataFrame,
) -> AdvancedAnalyticsResults:
    """Run clustering, trader rankings, statistical tests, and sentiment comparisons."""
    top_traders, worst_traders = rank_traders(trader_metrics)
    results = AdvancedAnalyticsResults(
        trader_clusters=cluster_traders(trader_metrics),
        top_traders=top_traders,
        worst_traders=worst_traders,
        statistical_tests=run_statistical_tests(trade_sentiment),
        sentiment_comparisons=compare_sentiment_groups(trade_sentiment),
    )
    LOGGER.info("Generated advanced analytics tables")
    return results


def save_advanced_analytics_tables(
    results: AdvancedAnalyticsResults,
    output_dir: Path,
) -> None:
    """Persist advanced analytics tables as CSV files."""
    output_dir.mkdir(parents=True, exist_ok=True)
    for table_name, dataframe in results.__dict__.items():
        dataframe.to_csv(output_dir / f"{table_name}.csv", index=False)
