"""Exploratory analysis for sentiment and trader-performance relationships."""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd


LOGGER = logging.getLogger(__name__)


@dataclass(frozen=True)
class AnalysisResults:
    """Named analysis tables generated by the EDA pipeline."""

    distribution_summary: pd.DataFrame
    correlation_matrix: pd.DataFrame
    sentiment_profitability: pd.DataFrame
    leverage_by_sentiment: pd.DataFrame
    symbol_performance: pd.DataFrame


def _profit_factor(closed_pnl: pd.Series) -> float:
    """Calculate gross profit divided by absolute gross loss."""
    gross_profit = closed_pnl[closed_pnl > 0].sum()
    gross_loss = closed_pnl[closed_pnl < 0].sum()
    if gross_loss < 0:
        return float(gross_profit / abs(gross_loss))
    if gross_profit > 0:
        return float("inf")
    return 0.0


def _win_rate(closed_pnl: pd.Series) -> float:
    """Calculate the share of profitable trades."""
    if closed_pnl.empty:
        return np.nan
    return float((closed_pnl > 0).mean())


def summarize_distributions(
    trade_sentiment: pd.DataFrame,
    daily_sentiment: pd.DataFrame,
    trader_metrics: pd.DataFrame,
) -> pd.DataFrame:
    """Create distribution summaries for key numeric metrics."""
    sources = {
        "trade": trade_sentiment,
        "daily": daily_sentiment,
        "trader": trader_metrics,
    }
    rows: list[dict[str, float | str]] = []

    for source_name, dataframe in sources.items():
        numeric_columns = dataframe.select_dtypes(include=[np.number]).columns
        for column in numeric_columns:
            series = dataframe[column].replace([np.inf, -np.inf], np.nan).dropna()
            if series.empty:
                continue
            description = series.describe(percentiles=[0.25, 0.5, 0.75])
            rows.append(
                {
                    "source": source_name,
                    "metric": column,
                    "count": float(description["count"]),
                    "mean": float(description["mean"]),
                    "std": float(description.get("std", np.nan)),
                    "min": float(description["min"]),
                    "p25": float(description["25%"]),
                    "median": float(description["50%"]),
                    "p75": float(description["75%"]),
                    "max": float(description["max"]),
                }
            )

    return pd.DataFrame(rows)


def compute_correlations(daily_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Compute Pearson correlations for daily numeric metrics."""
    numeric = daily_sentiment.select_dtypes(include=[np.number]).replace(
        [np.inf, -np.inf],
        np.nan,
    )
    numeric = numeric.dropna(axis=1, how="all")
    if numeric.shape[1] < 2:
        return pd.DataFrame()
    return numeric.corr(method="pearson")


def analyze_profitability_by_sentiment(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Compare trade profitability across sentiment classifications."""
    required_columns = {"classification", "closed_pnl"}
    missing_columns = sorted(required_columns - set(trade_sentiment.columns))
    if missing_columns:
        raise ValueError(f"Trade-sentiment data is missing columns: {missing_columns}")

    data = trade_sentiment.copy()
    data["classification"] = data["classification"].fillna("Unknown")
    grouped = data.groupby(["classification", "sentiment_score"], dropna=False)
    summary = grouped.agg(
        trades=("closed_pnl", "size"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        median_pnl=("closed_pnl", "median"),
        win_rate=("closed_pnl", _win_rate),
        pnl_volatility=("closed_pnl", lambda values: float(values.std(ddof=0))),
        avg_leverage=("leverage", "mean"),
        avg_size=("size", "mean"),
    ).reset_index()
    profit_factor = grouped["closed_pnl"].apply(_profit_factor).reset_index()
    profit_factor = profit_factor.rename(columns={"closed_pnl": "profit_factor"})
    summary = summary.merge(
        profit_factor,
        on=["classification", "sentiment_score"],
        how="left",
    )
    return summary.sort_values("sentiment_score", na_position="last").reset_index(drop=True)


def analyze_leverage_behavior(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Summarize leverage usage and outcomes by sentiment and leverage bucket."""
    required_columns = {"classification", "leverage_bucket", "closed_pnl"}
    missing_columns = sorted(required_columns - set(trade_sentiment.columns))
    if missing_columns:
        raise ValueError(f"Trade-sentiment data is missing columns: {missing_columns}")

    data = trade_sentiment.copy()
    data["classification"] = data["classification"].fillna("Unknown")
    data["leverage_bucket"] = data["leverage_bucket"].fillna("unknown")

    summary = data.groupby(
        ["classification", "sentiment_score", "leverage_bucket"],
        dropna=False,
    ).agg(
        trades=("closed_pnl", "size"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        win_rate=("closed_pnl", _win_rate),
        avg_leverage=("leverage", "mean"),
    ).reset_index()
    return summary.sort_values(
        ["sentiment_score", "leverage_bucket"],
        na_position="last",
    ).reset_index(drop=True)


def analyze_symbol_performance(trade_sentiment: pd.DataFrame) -> pd.DataFrame:
    """Rank symbols by profitability and trading behavior."""
    required_columns = {"symbol", "account", "closed_pnl"}
    missing_columns = sorted(required_columns - set(trade_sentiment.columns))
    if missing_columns:
        raise ValueError(f"Trade-sentiment data is missing columns: {missing_columns}")

    summary = trade_sentiment.groupby("symbol", dropna=False).agg(
        trades=("closed_pnl", "size"),
        active_traders=("account", "nunique"),
        total_pnl=("closed_pnl", "sum"),
        avg_pnl=("closed_pnl", "mean"),
        median_pnl=("closed_pnl", "median"),
        win_rate=("closed_pnl", _win_rate),
        avg_leverage=("leverage", "mean"),
        avg_size=("size", "mean"),
    ).reset_index()
    return summary.sort_values("total_pnl", ascending=False).reset_index(drop=True)


def run_exploratory_analysis(
    trade_sentiment: pd.DataFrame,
    daily_sentiment: pd.DataFrame,
    trader_metrics: pd.DataFrame,
) -> AnalysisResults:
    """Run the complete exploratory analysis suite."""
    results = AnalysisResults(
        distribution_summary=summarize_distributions(
            trade_sentiment,
            daily_sentiment,
            trader_metrics,
        ),
        correlation_matrix=compute_correlations(daily_sentiment),
        sentiment_profitability=analyze_profitability_by_sentiment(trade_sentiment),
        leverage_by_sentiment=analyze_leverage_behavior(trade_sentiment),
        symbol_performance=analyze_symbol_performance(trade_sentiment),
    )
    LOGGER.info("Generated exploratory analysis tables")
    return results


def save_analysis_tables(results: AnalysisResults, output_dir: Path) -> None:
    """Persist EDA tables as CSV files for review and reporting."""
    output_dir.mkdir(parents=True, exist_ok=True)
    for table_name, dataframe in results.__dict__.items():
        dataframe.to_csv(output_dir / f"{table_name}.csv", index=True)
